/* The following code was generated by JFlex 1.4.3 on 27/08/14 03:39 */

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 27/08/14 03:39 from the specification file
 * <tt>./Pascal.flex</tt>
 */
class LexicalAnalysisCalculator implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\20\1\16\1\0\1\20\1\15\22\0\1\20\1\0\1\60"+
    "\4\0\1\12\1\61\1\62\1\51\1\47\1\66\1\46\1\53\1\50"+
    "\12\1\1\52\1\65\1\55\1\54\1\56\2\0\1\3\1\2\1\2"+
    "\1\2\1\4\1\2\1\2\1\2\1\2\1\2\1\2\1\5\1\2"+
    "\1\6\1\2\1\2\1\2\1\7\1\2\1\10\1\2\1\2\1\2"+
    "\1\11\1\2\1\2\1\63\1\0\1\64\1\57\2\0\1\25\1\30"+
    "\1\32\1\41\1\31\1\37\1\24\1\45\1\42\1\2\1\44\1\27"+
    "\1\26\1\33\1\23\1\21\1\2\1\22\1\17\1\34\1\43\1\36"+
    "\1\40\1\11\1\35\1\2\1\13\1\0\1\14\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\0\2\5\11\2"+
    "\1\3\11\2\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\2\1\0\1\27\1\30\1\0"+
    "\4\2\1\31\1\32\15\2\1\33\10\2\1\34\1\2"+
    "\1\35\1\36\1\2\1\37\1\40\1\41\1\42\1\43"+
    "\1\2\1\44\6\2\1\45\1\46\4\2\1\47\2\2"+
    "\1\50\1\51\2\2\1\52\1\53\5\2\1\54\7\2"+
    "\1\55\4\2\1\56\1\2\1\57\1\60\1\61\1\2"+
    "\1\62\1\2\1\63\11\2\1\64\1\65\1\2\1\66"+
    "\1\67\2\2\1\70\1\2\1\71\1\72\2\2\1\73"+
    "\1\74\1\75\1\76\2\2\1\77\1\2\1\100\1\2"+
    "\1\101\1\2\1\72\1\2\1\102\1\103";

  private static int [] zzUnpackAction() {
    int [] result = new int[175];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\u0113\0\u014a\0\u0181"+
    "\0\u01b8\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb\0\u0302\0\u0339"+
    "\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483\0\u04ba\0\u04f1"+
    "\0\u0528\0\u055f\0\u0596\0\u0181\0\u0181\0\u0181\0\u0181\0\u05cd"+
    "\0\u0604\0\u0181\0\u063b\0\u0672\0\u0181\0\u0181\0\u0181\0\u0181"+
    "\0\u0181\0\u0181\0\u0181\0\u0181\0\u06a9\0\334\0\u06e0\0\u0181"+
    "\0\u0717\0\u074e\0\u0785\0\u07bc\0\u07f3\0\156\0\156\0\u082a"+
    "\0\u0861\0\u0898\0\u08cf\0\u0906\0\u093d\0\u0974\0\u09ab\0\u09e2"+
    "\0\u0a19\0\u0a50\0\u0a87\0\u0abe\0\156\0\u0af5\0\u0b2c\0\u0b63"+
    "\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f\0\u0c76\0\u0cad\0\u0ce4\0\156"+
    "\0\156\0\u0d1b\0\u0181\0\u0181\0\u0181\0\u0181\0\u0181\0\u0d52"+
    "\0\156\0\u0d89\0\u0dc0\0\u0df7\0\u0e2e\0\u0e65\0\u0e9c\0\156"+
    "\0\156\0\u0ed3\0\u0f0a\0\u0f41\0\u0f78\0\156\0\u0faf\0\u0fe6"+
    "\0\156\0\156\0\u101d\0\u1054\0\156\0\u108b\0\u10c2\0\u10f9"+
    "\0\u1130\0\u1167\0\u119e\0\156\0\u11d5\0\u120c\0\u1243\0\u127a"+
    "\0\u12b1\0\u12e8\0\u131f\0\156\0\u1356\0\u138d\0\u13c4\0\u13fb"+
    "\0\156\0\u1432\0\156\0\156\0\156\0\u1469\0\156\0\u14a0"+
    "\0\156\0\u14d7\0\u150e\0\u1545\0\u157c\0\u15b3\0\u15ea\0\u1621"+
    "\0\u1658\0\u168f\0\156\0\156\0\u16c6\0\156\0\156\0\u16fd"+
    "\0\u1734\0\156\0\u176b\0\156\0\u17a2\0\u17d9\0\u1810\0\156"+
    "\0\156\0\156\0\156\0\u1847\0\u187e\0\156\0\u18b5\0\156"+
    "\0\u18ec\0\156\0\u1923\0\156\0\u195a\0\156\0\156";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[175];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\2\3\1\4\5\3\1\5\1\6\1\0"+
    "\1\7\1\10\1\11\1\10\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\3\1\26\1\27\1\30\1\31\1\32\1\33\2\3"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\0\1\2\66\0\11\3\5\0\1\3\1\0"+
    "\25\3\22\0\10\3\1\55\5\0\1\3\1\0\25\3"+
    "\21\0\12\56\1\57\54\56\14\6\1\60\52\6\16\0"+
    "\1\61\140\0\11\3\5\0\1\3\1\0\10\3\1\62"+
    "\14\3\22\0\11\3\5\0\1\3\1\0\1\3\1\63"+
    "\2\3\1\64\20\3\22\0\11\3\5\0\1\3\1\0"+
    "\10\3\1\65\14\3\22\0\11\3\5\0\1\3\1\0"+
    "\1\3\1\66\14\3\1\67\6\3\22\0\11\3\5\0"+
    "\1\3\1\0\2\3\1\70\22\3\22\0\11\3\5\0"+
    "\1\3\1\0\1\3\1\71\10\3\1\72\12\3\22\0"+
    "\11\3\5\0\1\3\1\0\2\3\1\73\22\3\22\0"+
    "\11\3\5\0\1\3\1\0\4\3\1\74\3\3\1\75"+
    "\14\3\22\0\11\3\5\0\1\3\1\0\10\3\1\76"+
    "\14\3\22\0\10\3\1\55\5\0\1\3\1\0\6\3"+
    "\1\77\3\3\1\100\12\3\22\0\11\3\5\0\1\3"+
    "\1\0\2\3\1\101\1\3\1\102\20\3\22\0\11\3"+
    "\5\0\1\3\1\0\2\3\1\103\16\3\1\104\3\3"+
    "\22\0\11\3\5\0\1\3\1\0\2\3\1\105\11\3"+
    "\1\106\7\3\1\107\22\0\11\3\5\0\1\3\1\0"+
    "\4\3\1\110\20\3\22\0\11\3\5\0\1\3\1\0"+
    "\2\3\1\111\16\3\1\112\1\113\2\3\22\0\11\3"+
    "\5\0\1\3\1\0\21\3\1\114\2\3\1\115\22\0"+
    "\11\3\5\0\1\3\1\0\2\3\1\116\16\3\1\117"+
    "\3\3\22\0\11\3\5\0\1\3\1\0\12\3\1\120"+
    "\3\3\1\121\6\3\22\0\11\3\5\0\1\3\1\0"+
    "\12\3\1\122\12\3\75\0\1\123\65\0\1\124\67\0"+
    "\1\125\1\0\1\126\64\0\1\127\13\0\7\3\1\130"+
    "\1\3\5\0\1\3\1\0\13\3\1\130\11\3\33\0"+
    "\1\56\73\0\1\10\50\0\11\3\5\0\1\3\1\0"+
    "\13\3\1\131\11\3\22\0\11\3\5\0\1\3\1\0"+
    "\2\3\1\132\22\3\22\0\11\3\5\0\1\3\1\0"+
    "\11\3\1\133\13\3\22\0\11\3\5\0\1\3\1\0"+
    "\1\134\10\3\1\135\13\3\22\0\11\3\5\0\1\3"+
    "\1\0\13\3\1\136\11\3\22\0\11\3\5\0\1\3"+
    "\1\0\1\3\1\137\23\3\22\0\11\3\5\0\1\3"+
    "\1\0\20\3\1\140\4\3\22\0\11\3\5\0\1\3"+
    "\1\0\20\3\1\141\4\3\22\0\11\3\5\0\1\3"+
    "\1\0\7\3\1\142\15\3\22\0\11\3\5\0\1\3"+
    "\1\0\13\3\1\143\11\3\22\0\11\3\5\0\1\3"+
    "\1\0\3\3\1\144\21\3\22\0\11\3\5\0\1\145"+
    "\1\0\25\3\22\0\11\3\5\0\1\3\1\0\20\3"+
    "\1\146\4\3\22\0\11\3\5\0\1\3\1\0\12\3"+
    "\1\147\12\3\22\0\11\3\5\0\1\150\1\0\25\3"+
    "\22\0\11\3\5\0\1\3\1\0\13\3\1\151\11\3"+
    "\22\0\11\3\5\0\1\3\1\0\6\3\1\152\16\3"+
    "\22\0\11\3\5\0\1\3\1\0\1\153\24\3\22\0"+
    "\11\3\5\0\1\3\1\0\10\3\1\154\14\3\22\0"+
    "\11\3\5\0\1\3\1\0\1\3\1\155\23\3\22\0"+
    "\11\3\5\0\1\3\1\0\1\3\1\156\23\3\22\0"+
    "\11\3\5\0\1\3\1\0\6\3\1\157\16\3\22\0"+
    "\11\3\5\0\1\3\1\0\12\3\1\160\12\3\22\0"+
    "\11\3\5\0\1\3\1\0\13\3\1\161\11\3\22\0"+
    "\11\3\5\0\1\3\1\0\21\3\1\162\3\3\22\0"+
    "\11\3\5\0\1\3\1\0\17\3\1\163\5\3\22\0"+
    "\11\3\5\0\1\3\1\0\15\3\1\164\7\3\22\0"+
    "\11\3\5\0\1\3\1\0\13\3\1\165\11\3\22\0"+
    "\3\3\1\166\5\3\5\0\1\3\1\0\10\3\1\166"+
    "\14\3\22\0\11\3\5\0\1\3\1\0\3\3\1\167"+
    "\5\3\1\170\13\3\22\0\11\3\5\0\1\3\1\0"+
    "\23\3\1\171\1\3\22\0\11\3\5\0\1\3\1\0"+
    "\10\3\1\172\14\3\22\0\11\3\5\0\1\3\1\0"+
    "\2\3\1\173\22\3\22\0\11\3\5\0\1\3\1\0"+
    "\2\3\1\174\22\3\22\0\11\3\5\0\1\3\1\0"+
    "\4\3\1\175\20\3\22\0\11\3\5\0\1\3\1\0"+
    "\10\3\1\176\14\3\22\0\11\3\5\0\1\3\1\0"+
    "\13\3\1\177\11\3\22\0\11\3\5\0\1\3\1\0"+
    "\21\3\1\200\3\3\22\0\11\3\5\0\1\3\1\0"+
    "\10\3\1\201\14\3\22\0\11\3\5\0\1\202\1\0"+
    "\25\3\22\0\11\3\5\0\1\3\1\0\10\3\1\203"+
    "\14\3\22\0\11\3\5\0\1\3\1\0\10\3\1\204"+
    "\14\3\22\0\11\3\5\0\1\3\1\0\12\3\1\205"+
    "\12\3\22\0\11\3\5\0\1\3\1\0\17\3\1\206"+
    "\5\3\22\0\11\3\5\0\1\3\1\0\10\3\1\207"+
    "\14\3\22\0\11\3\5\0\1\3\1\0\11\3\1\210"+
    "\13\3\22\0\11\3\5\0\1\3\1\0\24\3\1\211"+
    "\22\0\11\3\5\0\1\3\1\0\6\3\1\212\16\3"+
    "\22\0\11\3\5\0\1\3\1\0\12\3\1\213\12\3"+
    "\22\0\11\3\5\0\1\3\1\0\21\3\1\214\3\3"+
    "\22\0\6\3\1\215\2\3\5\0\1\3\1\0\1\3"+
    "\1\215\23\3\22\0\11\3\5\0\1\3\1\0\1\3"+
    "\1\216\23\3\22\0\11\3\5\0\1\3\1\0\10\3"+
    "\1\217\14\3\22\0\11\3\5\0\1\3\1\0\10\3"+
    "\1\220\14\3\22\0\11\3\5\0\1\3\1\0\4\3"+
    "\1\221\20\3\22\0\11\3\5\0\1\3\1\0\1\3"+
    "\1\222\23\3\22\0\11\3\5\0\1\3\1\0\14\3"+
    "\1\223\10\3\22\0\11\3\5\0\1\3\1\0\6\3"+
    "\1\224\16\3\22\0\11\3\5\0\1\3\1\0\10\3"+
    "\1\225\14\3\22\0\11\3\5\0\1\3\1\0\12\3"+
    "\1\226\12\3\22\0\11\3\5\0\1\3\1\0\13\3"+
    "\1\227\11\3\22\0\11\3\5\0\1\3\1\0\4\3"+
    "\1\230\20\3\22\0\11\3\5\0\1\3\1\0\13\3"+
    "\1\231\11\3\22\0\11\3\5\0\1\3\1\0\10\3"+
    "\1\232\14\3\22\0\11\3\5\0\1\3\1\0\13\3"+
    "\1\233\11\3\22\0\11\3\5\0\1\3\1\0\6\3"+
    "\1\234\16\3\22\0\5\3\1\235\3\3\5\0\1\3"+
    "\1\0\12\3\1\235\12\3\22\0\11\3\5\0\1\3"+
    "\1\0\4\3\1\236\20\3\22\0\11\3\5\0\1\3"+
    "\1\0\20\3\1\237\4\3\22\0\11\3\5\0\1\3"+
    "\1\0\20\3\1\240\4\3\22\0\11\3\5\0\1\3"+
    "\1\0\13\3\1\241\11\3\22\0\11\3\5\0\1\3"+
    "\1\0\20\3\1\242\4\3\22\0\11\3\5\0\1\3"+
    "\1\0\1\3\1\243\23\3\22\0\11\3\5\0\1\3"+
    "\1\0\1\3\1\244\23\3\22\0\11\3\5\0\1\3"+
    "\1\0\21\3\1\245\3\3\22\0\11\3\5\0\1\3"+
    "\1\0\2\3\1\246\22\3\22\0\2\3\1\247\6\3"+
    "\5\0\1\3\1\0\4\3\1\247\20\3\22\0\11\3"+
    "\5\0\1\3\1\0\5\3\1\250\17\3\22\0\11\3"+
    "\5\0\1\3\1\0\22\3\1\251\2\3\22\0\11\3"+
    "\5\0\1\3\1\0\20\3\1\252\4\3\22\0\11\3"+
    "\5\0\1\3\1\0\2\3\1\253\22\3\22\0\4\3"+
    "\1\254\4\3\5\0\1\3\1\0\6\3\1\254\16\3"+
    "\22\0\11\3\5\0\1\3\1\0\1\3\1\255\23\3"+
    "\22\0\11\3\5\0\1\3\1\0\12\3\1\256\12\3"+
    "\22\0\11\3\5\0\1\3\1\0\10\3\1\257\14\3"+
    "\21\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6545];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\4\1\1\0\1\1\1\11\23\1\4\11\2\1"+
    "\1\11\2\1\10\11\1\1\1\0\1\1\1\11\1\0"+
    "\41\1\5\11\130\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[175];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	   
	   private Symbol symbol(int type) {
		   return new Symbol(type, yyline, yycolumn);
   	   }
   	
 	   private Symbol symbol(int type, Object val) {
		   return new Symbol(type, yyline, yycolumn, val);
   	   }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexicalAnalysisCalculator(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LexicalAnalysisCalculator(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 176) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 31: 
          { return symbol(sym.ASSIGMENT);
          }
        case 68: break;
        case 8: 
          { return symbol(sym.DIV, new Integer(yyline + 1));
          }
        case 69: break;
        case 47: 
          { return symbol(sym.CASE, new Integer(yyline + 1));
          }
        case 70: break;
        case 49: 
          { return symbol(sym.THEN, new Integer(yyline + 1));
          }
        case 71: break;
        case 67: 
          { return symbol(sym.PROCEDURE, new Integer(yyline + 1));
          }
        case 72: break;
        case 15: 
          { return symbol(sym.CIRCUNFLEX, new Integer(yyline + 1));
          }
        case 73: break;
        case 42: 
          { return symbol(sym.VAR, new Integer(yyline + 1));
          }
        case 74: break;
        case 54: 
          { return symbol(sym.BEGIN, new Integer(yyline + 1));
          }
        case 75: break;
        case 37: 
          { return symbol(sym.AND, new Integer(yyline + 1));
          }
        case 76: break;
        case 66: 
          { return symbol(sym.FUNCTION, new Integer(yyline + 1));
          }
        case 77: break;
        case 65: 
          { return symbol(sym.FORWARD, new Integer(yyline + 1));
          }
        case 78: break;
        case 40: 
          { return symbol(sym.NOT, new Integer(yyline + 1));
          }
        case 79: break;
        case 25: 
          { return symbol(sym.OR, new Integer(yyline + 1));
          }
        case 80: break;
        case 16: 
          { return symbol(sym.DOUBLEQUOTE, new Integer(yyline + 1));
          }
        case 81: break;
        case 19: 
          { return symbol(sym.LBRACKET);
          }
        case 82: break;
        case 52: 
          { return symbol(sym.ARRAY, new Integer(yyline + 1));
          }
        case 83: break;
        case 64: 
          { return symbol(sym.PROGRAM, new Integer(yyline + 1));
          }
        case 84: break;
        case 44: 
          { return symbol(sym.DIVEXTENSION, new Integer(yyline + 1));
          }
        case 85: break;
        case 10: 
          { return symbol(sym.COLON, new Integer(yyline + 1));
          }
        case 86: break;
        case 24: 
          { System.out.println("Comment: " + yytext());
          }
        case 87: break;
        case 13: 
          { return symbol(sym.LESSTHEN, new Integer(yyline + 1));
          }
        case 88: break;
        case 12: 
          { return symbol(sym.EQUALS, new Integer(yyline + 1));
          }
        case 89: break;
        case 32: 
          { return symbol(sym.DOUBLEDOT, new Integer(yyline + 1));
          }
        case 90: break;
        case 57: 
          { return symbol(sym.UNTIL, new Integer(yyline + 1));
          }
        case 91: break;
        case 38: 
          { return symbol(sym.MOD, new Integer(yyline + 1));
          }
        case 92: break;
        case 23: 
          { return symbol(sym.STRINGCHARACTER);
          }
        case 93: break;
        case 62: 
          { return symbol(sym.LETTER);
          }
        case 94: break;
        case 5: 
          { /*ignore*/
          }
        case 95: break;
        case 18: 
          { return symbol(sym.RPARENT);
          }
        case 96: break;
        case 30: 
          { return symbol(sym.IF, new Integer(yyline + 1));
          }
        case 97: break;
        case 51: 
          { return symbol(sym.WITH, new Integer(yyline + 1));
          }
        case 98: break;
        case 59: 
          { return symbol(sym.PACKED, new Integer(yyline + 1));
          }
        case 99: break;
        case 45: 
          { return symbol(sym.GOTO, new Integer(yyline + 1));
          }
        case 100: break;
        case 26: 
          { return symbol(sym.OF, new Integer(yyline + 1));
          }
        case 101: break;
        case 20: 
          { return symbol(sym.RBRACKET);
          }
        case 102: break;
        case 4: 
          { return symbol(sym.SINGLEQUOTE, new Integer(yyline + 1));
          }
        case 103: break;
        case 9: 
          { return symbol(sym.TIMES, new Integer(yyline + 1));
          }
        case 104: break;
        case 60: 
          { return symbol(sym.REPEAT, new Integer(yyline + 1));
          }
        case 105: break;
        case 58: 
          { return symbol(sym.EXTERNAL);
          }
        case 106: break;
        case 33: 
          { return symbol(sym.LESSTHENEQUALS, new Integer(yyline + 1));
          }
        case 107: break;
        case 61: 
          { return symbol(sym.RECORD, new Integer(yyline + 1));
          }
        case 108: break;
        case 48: 
          { return symbol(sym.TYPE, new Integer(yyline + 1));
          }
        case 109: break;
        case 35: 
          { return symbol(sym.GREATERTHENEQUALS, new Integer(yyline + 1));
          }
        case 110: break;
        case 7: 
          { return symbol(sym.PLUS, new Integer(yyline + 1));
          }
        case 111: break;
        case 56: 
          { return symbol(sym.WHILE, new Integer(yyline + 1));
          }
        case 112: break;
        case 55: 
          { return symbol(sym.CONST, new Integer(yyline + 1));
          }
        case 113: break;
        case 3: 
          { return symbol(sym.SCALEFACTOR);
          }
        case 114: break;
        case 63: 
          { return symbol(sym.DOWNTO, new Integer(yyline + 1));
          }
        case 115: break;
        case 43: 
          { return symbol(sym.FOR, new Integer(yyline + 1));
          }
        case 116: break;
        case 50: 
          { return symbol(sym.FILE, new Integer(yyline + 1));
          }
        case 117: break;
        case 27: 
          { return symbol(sym.TO, new Integer(yyline + 1));
          }
        case 118: break;
        case 39: 
          { return symbol(sym.END, new Integer(yyline + 1));
          }
        case 119: break;
        case 41: 
          { return symbol(sym.NIL, new Integer(yyline + 1));
          }
        case 120: break;
        case 21: 
          { return symbol(sym.SEMICOLON);
          }
        case 121: break;
        case 34: 
          { return symbol(sym.DIFF, new Integer(yyline + 1));
          }
        case 122: break;
        case 6: 
          { return symbol(sym.MINUS, new Integer(yyline + 1));
          }
        case 123: break;
        case 14: 
          { return symbol(sym.GREATERTHEN, new Integer(yyline + 1));
          }
        case 124: break;
        case 53: 
          { return symbol(sym.LABEL, new Integer(yyline + 1));
          }
        case 125: break;
        case 46: 
          { return symbol(sym.ELSE, new Integer(yyline + 1));
          }
        case 126: break;
        case 36: 
          { return symbol(sym.SET, new Integer(yyline + 1));
          }
        case 127: break;
        case 2: 
          { return symbol(sym.IDENTIFIER, new String(yytext()));
          }
        case 128: break;
        case 17: 
          { return symbol(sym.LPARENT);
          }
        case 129: break;
        case 28: 
          { return symbol(sym.DO, new Integer(yyline + 1));
          }
        case 130: break;
        case 22: 
          { return symbol(sym.COMMA);
          }
        case 131: break;
        case 1: 
          { return symbol(sym.DIGITSEQUENCE, new String(yytext()));
          }
        case 132: break;
        case 29: 
          { return symbol(sym.IN, new Integer(yyline + 1));
          }
        case 133: break;
        case 11: 
          { return symbol(sym.DOT);
          }
        case 134: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
