
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Aug 27 06:45:31 BRT 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RPARENT = 38;
  public static final int LPARENT = 37;
  public static final int LESSTHEN = 65;
  public static final int FUNCTION = 11;
  public static final int LBRACKET = 39;
  public static final int GREATERTHENEQUALS = 68;
  public static final int CONST = 4;
  public static final int WITH = 28;
  public static final int PACKED = 12;
  public static final int EQUALS = 63;
  public static final int STRINGCHARACTERCLOSURE = 62;
  public static final int DIVEXTENSION = 31;
  public static final int CASE = 27;
  public static final int REPEAT = 19;
  public static final int ARRAY = 13;
  public static final int FORWARD = 7;
  public static final int MINUS = 41;
  public static final int FOR = 21;
  public static final int SEMICOLON = 47;
  public static final int NOT = 30;
  public static final int AND = 33;
  public static final int RECORD = 34;
  public static final int TYPE = 5;
  public static final int NIL = 29;
  public static final int IN = 69;
  public static final int OR = 32;
  public static final int COMMA = 48;
  public static final int DOUBLEDOT = 50;
  public static final int DIV = 43;
  public static final int BEGIN = 8;
  public static final int UNTIL = 20;
  public static final int SCALEFACTOR = 70;
  public static final int DIGIT = 56;
  public static final int PLUS = 42;
  public static final int SINGLEQUOTE = 51;
  public static final int IF = 24;
  public static final int DOT = 49;
  public static final int OF = 14;
  public static final int EOF = 0;
  public static final int RBRACKET = 40;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int NUMBER = 58;
  public static final int MOD = 45;
  public static final int CIRCUNFLEX = 54;
  public static final int LESSTHENEQUALS = 66;
  public static final int TIMES = 44;
  public static final int COLON = 46;
  public static final int GREATERTHEN = 67;
  public static final int EXTERNAL = 15;
  public static final int ELSE = 26;
  public static final int LETTER = 59;
  public static final int DOUBLEQUOTE = 52;
  public static final int FILE = 36;
  public static final int TO = 22;
  public static final int GOTO = 16;
  public static final int WHILE = 17;
  public static final int THEN = 25;
  public static final int END = 9;
  public static final int STRING = 60;
  public static final int DIGITSEQUENCE = 57;
  public static final int DIFF = 64;
  public static final int DOWNTO = 23;
  public static final int STRINGCHARACTER = 61;
  public static final int ASSIGMENT = 53;
  public static final int LABEL = 3;
  public static final int VAR = 6;
  public static final int PROCEDURE = 10;
  public static final int DO = 18;
  public static final int SET = 35;
  public static final int IDENTIFIER = 55;
}

