
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jul 19 15:36:04 GMT-03:00 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 7;
  public static final int SEMICOLON = 13;
  public static final int PLUS = 5;
  public static final int RPAREN = 3;
  public static final int DIGIT = 8;
  public static final int END = 20;
  public static final int IDENTIFIER = 17;
  public static final int LPAREN = 2;
  public static final int COLON = 12;
  public static final int PROGRAM = 16;
  public static final int LETTER = 10;
  public static final int BEGIN = 19;
  public static final int STRING = 11;
  public static final int COMMA = 14;
  public static final int EOF = 0;
  public static final int NUMBER = 9;
  public static final int DIV = 6;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int DOT = 15;
  public static final int IDENTIFIERLIST = 18;
}

